version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: household-expenses-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-household_expenses}
      POSTGRES_USER: ${POSTGRES_USER:-household_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_secure_password}
      TZ: "Asia/Tokyo"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-household_user} -d ${POSTGRES_DB:-household_expenses}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data:
    driver: local
