plugins:
  - prettier-plugin-java
overrides:
  - files: "*.java"
    options:
      tabWidth: 4
      useTabs: false
      printWidth: 120
      trailingComma: "none"
      bracketSpacing: true
      arrowParens: avoid
      endOfLine: lf
